Configure nat instance with an in and an out interface, essentially we will have 2 interfaces now just like a classic linux router

diff --git a/templates/nat.sh.erb b/templates/nat.sh.erb
--- a/templates/nat.sh.erb
+++ b/templates/nat.sh.erb
@@ -30,7 +30,8 @@
 . /usr/local/lib/util.sh
 
 # This variable is generated by puppet
-NAT_INTERFACE="<%= @nat_interface %>"
+NAT_IN_INTERFACE="<%= @nat_in_interface %>"
+NAT_OUT_INTERFACE="<%= @nat_out_interface %>"
 
 function __get_mac {
     if [[ -z "${1}" ]]; then echo "Usage: $FUNCNAME [interface]"; return 1; fi
@@ -125,16 +126,17 @@ function get_main_rtb() {
 }
 
 log "Beginning Port Address Translator (PAT) configuration..."
-log "Determining the MAC address on ${NAT_INTERFACE}..."
-ETH_MAC=$(__get_mac ${NAT_INTERFACE}) ||
-    die "Unable to determine MAC address on ${NAT_INTERFACE}."
-log "Found MAC ${ETH_MAC} for ${NAT_INTERFACE}."
+log "Determining the MAC address on ${NAT_OUT_INTERFACE}..."
+ETH_OUT_MAC=$(__get_mac ${NAT_OUT_INTERFACE}) ||
+    die "Unable to determine MAC address on ${NAT_OUT_INTERFACE}."
+log "Found MAC ${ETH_OUT_MAC} for ${NAT_OUT_INTERFACE}."
 
-VPC_CIDR_URI="http://169.254.169.254/latest/meta-data/network/interfaces/macs/${ETH_MAC}/vpc-ipv4-cidr-block"
+ETH_IN_MAC=$(__get_mac ${NAT_IN_INTERFACE}) ||
+    die "Unable to determin MAC address on ${NAT_IN_INTERFACE}."
+log "Found MAC ${ETH_IN_MAC} for ${NAT_IN_INTERFACE}."
+
+VPC_CIDR_URI="http://169.254.169.254/latest/meta-data/network/interfaces/macs/${ETH_OUT_MAC}/vpc-ipv4-cidr-block"
 log "Metadata location for vpc ipv4 range: ${VPC_CIDR_URI}"
-
-ENI_ID_URI="http://169.254.169.254/latest/meta-data/network/interfaces/macs/${ETH_MAC}/interface-id"
-log "Metadata for location of ${NAT_INTERFACE} ENI id: ${ENI_ID_URI}"
 
 VPC_CIDR_RANGE=$(curl --retry 3 --silent --fail ${VPC_CIDR_URI})
 if [ $? -ne 0 ]; then
@@ -146,8 +148,8 @@ fi
 
 log "Enabling PAT..."
 sysctl -q -w net.ipv4.ip_forward=1 net.ipv4.conf.all.send_redirects=0 && (
-    iptables -t nat -C POSTROUTING -o ${NAT_INTERFACE} -s ${VPC_CIDR_RANGE} -j MASQUERADE 2> /dev/null ||
-    iptables -t nat -A POSTROUTING -o ${NAT_INTERFACE} -s ${VPC_CIDR_RANGE} -j MASQUERADE ) ||
+    iptables -t nat -C POSTROUTING -o ${NAT_OUT_INTERFACE} -s ${VPC_CIDR_RANGE} -j MASQUERADE 2> /dev/null ||
+    iptables -t nat -A POSTROUTING -o ${NAT_OUT_INTERFACE} -s ${VPC_CIDR_RANGE} -j MASQUERADE ) ||
         die
 
 # Some debugging output here
@@ -162,7 +164,9 @@ INSTANCE_ID=$(__get_instance_id)
 VPC_ID=$(get_vpc_id "${INSTANCE_ID}")
 MAIN_RT=$(get_main_rtb "${VPC_ID}")
 PRIVATE_SUBNETS=($(get_private_subnets "${VPC_ID}"))
-ENI_ID=$(curl --retry 3 --silent --fail "${ENI_ID_URI}")
+
+ENI_IN_ID=$(curl --retry 3 --silent --fail "http://169.254.169.254/latest/meta-data/network/interfaces/macs/${ETH_IN_MAC}/interface-id")
+ENI_OUT_ID=$(curl --retry 3 --silent --fail "http://169.254.169.254/latest/meta-data/network/interfaces/macs/${ETH_OUT_MAC}/interface-id")
 
 if [ -z "${PRIVATE_SUBNETS}" ]; then
     log "No private subnet found to modify HA NAT"
@@ -177,8 +181,8 @@ else
         elif [ -z "${rtb_id}" ]; then
             log "WARNING: "${subnet}" is not associated with a route table. Skipping this subnet"
         else
-            log "Replacing default route for ${rtb_id} to point to instance ${instance_id} (${ENI_ID})"
-            aws --region "${REGION}" ec2 replace-route --route-table-id "${rtb_id}" --destination-cidr-block 0.0.0.0/0 --network-interface-id "${ENI_ID}"
+            log "Replacing default route for ${rtb_id} to point to instance ${instance_id} (${ENI_IN_ID})"
+            aws --region "${REGION}" ec2 replace-route --route-table-id "${rtb_id}" --destination-cidr-block 0.0.0.0/0 --network-interface-id "${ENI_IN_ID}"
         fi
     done
 fi
@@ -187,15 +191,17 @@ if [ $? -ne 0 ]; then
     die
 fi
 
-log "Disabling SourceDestCheck"
-SOURCEDEST_CHECK=$(aws ec2 describe-network-interfaces --network-interface-ids "${ENI_ID}" --query 'NetworkInterfaces[].SourceDestCheck' --region "${REGION}" --output text)
+for eni in ${ENI_IN_ID} ${ENI_OUT_ID}; do
+    log "Disabling SourceDestCheck for eni: ${eni}"
+    SOURCEDEST_CHECK=$(aws ec2 describe-network-interfaces --network-interface-ids "${eni}" --query 'NetworkInterfaces[].SourceDestCheck' --region "${REGION}" --output text)
 
-# This needs to happen otherwise the NAT will not work
-if [[ "${SOURCEDEST_CHECK}" != 'False' ]] || [[ "${SOURCEDEST_CHECK}" != 'false' ]]; then
-    log "Setting SourceDestCheck to false"
-    aws ec2 modify-network-interface-attribute --network-interface-id "${ENI_ID}" --no-source-dest-check --region "${REGION}" ||
-        die "Unable to set SourceDestCheck to false"
-fi
+    # This needs to happen otherwise the NAT will not work
+    if [[ "${SOURCEDEST_CHECK}" != 'False' ]] || [[ "${SOURCEDEST_CHECK}" != 'false' ]]; then
+        log "Setting SourceDestCheck to false for eni: ${eni}"
+        aws ec2 modify-network-interface-attribute --network-interface-id "${eni}" --no-source-dest-check --region "${REGION}" ||
+            die "Unable to set SourceDestCheck to false"
+    fi
+done
 
 log "Configuration of HA Nat completed"
 exit 0
