Remove util.sh and start using nubis-lib.sh which is provided by nubis-base

diff --git a/templates/nat.sh.erb b/templates/nat.sh.erb
--- a/templates/nat.sh.erb
+++ b/templates/nat.sh.erb
@@ -27,51 +27,12 @@
 # Enable for debugging
 #set -x
 
-. /usr/local/lib/util.sh
+# Common functions
+[ -e /usr/local/lib/nubis/nubis-lib.sh ] && . /usr/local/lib/nubis/nubis-lib.sh || exit 1
 
 # This variable is generated by puppet
 NAT_IN_INTERFACE="<%= @nat_in_interface %>"
 NAT_OUT_INTERFACE="<%= @nat_out_interface %>"
-
-function __get_mac {
-    if [[ -z "${1}" ]]; then echo "Usage: $FUNCNAME [interface]"; return 1; fi
-
-    local attempts=10
-    local interface=$1
-    false
-    while [[ "${?}" -gt 0 ]]; do
-        [[ "${attempts}" -eq 0 ]] && return
-        mac_addr=$(cat /sys/class/net/${interface}/address)
-        if [ "${?}" -gt 0 ]; then
-            let attempts--
-            sleep 3
-            false
-        fi
-    done
-    echo "${mac_addr}"
-}
-
-function __get_availability_zone() {
-    local availability_zone=$(curl --retry 3 --retry-delay 0 -s -fq http://169.254.169.254/latest/meta-data/placement/availability-zone)
-    echo "${availability_zone}"
-}
-
-function __get_instance_id() {
-    local instance_id=$(curl --retry 3 --retry-delay 0 -s -fq http://169.254.169.254/latest/meta-data/instance-id)
-    echo "${instance_id}"
-}
-
-function __get_eni_id() {
-    if [ -z "$1" ]; then echo "Usage: $FUNCNAME [interface]"; return 1; fi
-
-    local interface=$1
-    local mac_addr=$(__get_mac "${interface}")
-
-    eni_id=$(curl --retry 5 --retry-delay 0 -s -fq "http://169.254.169.254/latest/meta-data/network/interfaces/macs/${mac_addr}/interface-id") ||
-        die "Unable to determine ENI ID for interface ${interface} with MAC address ${mac_addr}"
-    log "ENI ID for interface ${interface} is ${eni_id}"
-    echo "${eni_id}"
-}
 
 function get_vpc_id() {
     if [ -z "$1" ]; then echo "Usage: $FUNCNAME [instance id]"; return 1; fi
@@ -171,13 +132,13 @@ log "$(iptables -n -t nat -L POSTROUTING)"
 
 log "Configuration of NAT/PAT complete."
 
-AVAILABILITY_ZONE=$(__get_availability_zone)
-INSTANCE_ID=$(__get_instance_id)
+AVAILABILITY_ZONE=$(get_availability_zone)
+INSTANCE_ID=$(get_instance_id)
 VPC_ID=$(get_vpc_id "${INSTANCE_ID}")
 MAIN_RT=$(get_main_rtb "${VPC_ID}")
 PRIVATE_SUBNETS=($(get_private_subnets "${VPC_ID}"))
-ENI_IN_ID=$(__get_eni_id "${NAT_IN_INTERFACE}")
-ENI_OUT_ID=$(__get_eni_id "${NAT_OUT_INTERFACE}")
+ENI_IN_ID=$(get_eni_id "${NAT_IN_INTERFACE}")
+ENI_OUT_ID=$(get_eni_id "${NAT_OUT_INTERFACE}")
 
 if [ -z "${PRIVATE_SUBNETS}" ]; then
     log "No private subnet found to modify HA NAT"
@@ -192,14 +153,14 @@ else
         elif [ -z "${rtb_id}" ]; then
             log "WARNING: "${subnet}" is not associated with a route table. Skipping this subnet"
         else
-            log "Replacing default route for ${rtb_id} to point to instance ${instance_id} (${ENI_IN_ID})"
+            log "Replacing default route for ${rtb_id} to point to instance ${INSTANCE_ID} (${ENI_IN_ID})"
             aws --region "${REGION}" ec2 replace-route --route-table-id "${rtb_id}" --destination-cidr-block 0.0.0.0/0 --network-interface-id "${ENI_IN_ID}"
         fi
     done
 fi
 
 if [ $? -ne 0 ]; then
-    die
+    die "Unable to configure NAT"
 fi
 
 for eni in ${ENI_IN_ID} ${ENI_OUT_ID}; do
